# Generated by Django 5.0.2 on 2024-03-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupstd',
            name='Rollno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signupstd',
            name='branch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signupstd',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
