# Generated by Django 5.0.2 on 2024-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_signupstd_rollno_alter_signupstd_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupteach',
            name='teachID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
